name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator
          plugin_repositories_pinned: 3
          plugin_traffic: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_lines: yes
          plugin_lines_history_limit: 5
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base, history
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
