name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_repositories: yes
          plugin_repositories_pinned: 3
          plugin_repositories_affiliations: owner, collaborator
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used


