name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata

